install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential cmake uuid-dev g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
  - git checkout 2.5.0
  - cmake .
  - make
  - sudo make install
  - task --version
  - cd test
  - make
script:
  - ./run_all
